### ISSUE TITLE
Can you do a pool request for your layer in the official caffe branch?

### ISSUE THREAD

**Issue by Coderx7** [kevinlin311tw/caffe-augmentation#3]
Hello, 
Can you do it? 
It is a very nice addition to the official build. 
I wanted to use this build, but since I am using the latest caffe branch, and thus its new features, My models dont run in this branch. 
How ever if you could do a PR in caffe it would benifit us all. 
or if that is not possible, Would you please very briefly guide me how I can integrate this layer into the official branch?
Best Regards

**Comment by kevinlin311tw** [comment]
Sure, I will do a PR after finishing my current project...
Since these augmentation functions are easy to implement, you can simply follow my [submission history](https://github.com/kevinlin311tw/caffe-augmentation/commit/84e52e3fdcebbaec1e0e500874292f31aa65822e)
You may check `data_transformer.cpp` and `caffe.proto` to find the codes.

**Comment by Coderx7** [comment]
Thats great
Thank you very much :)

**Comment by EvanZ** [comment]
This is awesome!

**Comment by Coderx7** [comment]
@kevinlin311tw :by the way does this support test time augmentation as well? 
how does dynamic augmentation is reflected in test time, I once use cropping, and it decreased my accuracy very badly! I see others using it and getting better accuracies, whats the cause ?
